### ISSUE TITLE
understanding and using the "AutoStart"/service like feature of TeamStatusV2

### ISSUE THREAD

**Issue by binderth** [AntoineGS/TeamsStatusV2#20]
I installed and configured TeamsStatusv2 as described. And there's the link for TeamsStatusV2. There's the link to "Start.cmd" in my Autostart folder, but the script won't start with the next reboot.
Where can I look into to that and make sure, the script is running?

**Comment by AntoineGS** [comment]
Unfortunately since this is not a service the only indicator is the 'Powershell.exe' process that runs in the background, though if you have other scripts then I do not know of a way to differentiate them.
If the startup will not work, you could try scheduling the bat file through the Windows Task Scheduler as a 'at logon' script and see if it works.
