### ISSUE TITLE
Support for New Teams

### ISSUE THREAD

**Issue by bezibaerchen** [AntoineGS/TeamsStatusV2#23]
Hi Antoine,

do you hold any knowledge where "New Teams" stores it's logfiles? I am currently piloting the client and script stopped working as logfile location or even logging changed completely. As I heavily use this script to control my busy light I'd be highly interested in getting "New Teams" working.

**Comment by bezibaerchen** [comment]
I happen to be an admin of our tenant and enabled it for a pilot group.
Trust me, this "new" thing is anything but stable, but someone has to test it. Biggest advantages from my perspective so far:

- way snappier
- possibility to add more than 1 work account (important for us, as we have users working in multiple tenants)

I am however really not sure where to find the logs to potentially parse for your PS-Script and my busylight not working sucks when working from home ;-)

So if you have any idea as of how to potentially locate I'd highly appreciate.

**Comment by AntoineGS** [comment]
The 'easy aka bruteforce' approach I would take is to search some common keywords that were part of the old log file in a wide search from the C: drive (or whichever one you have your apps installed) and hope it finds something.
I typically use the Find feature of Multi Commander (File Explorer replacement) to do this as Windows never seems to have gotten searching working at a reasonable speed.
Any other method of doing 'Find in Files' would work.
I would have pasted some examples from the log file but I have no power since yesterday due to a wave of freezing rain in my area lol.

**Comment by pulimento** [comment]
As far as I see, the process name changes, and the logs are in another path (for now, because those are two separate apps, "Teams" and "Teams Preview".
Will take a look at paths/logs when I have time

**Comment by bezibaerchen** [comment]
> As far as I see, the process name changes, and the logs are in another path (for now, because those are two separate apps, "Teams" and "Teams Preview". Will take a look at paths/logs when I have time

That would be truly appreciated. Preview still clearly a preview but it is way more snappy, despite lacking functionalities.

**Comment by AntoineGS** [comment]
I started rewriting this project in Rust as a means to learn the language and stumbled upon this while figuring out if there is a way to get away from tailing a log file:
https://support.microsoft.com/en-us/office/connect-third-party-devices-to-teams-aabca9f2-47bb-407f-9f9b-81a104a883d6
Do you know if the new Teams has a similar option to turn on the local API?
If so the re-write might be more beneficial than I had thought 🤣

**Comment by binderth** [comment]
I don't know anything about the new Teams, as my company doesn't have an early beta-testing in place for it.
But I bought a Stream Deck last week and was about to propose to you using the local API, as there must be some way to 

1. get info on a current meeting (aka `activity`), as the Stream Deck's icons are greyed if I'm not online
2. get info on use of microphone (this one's new for TeamsStatusV2 and great to know!) and camera (aka `webcam`), as there's two icon states for it

What I think, the local API (at least for present Teams) is lacking: the "real" state (aka `status`: Available, Busy, Do not disturb, ...). That is always nice at least for my use case to show my states and if I'm in a meeting right now outside of my study room.

**Comment by pulimento** [comment]
Unfortunately, can't find this API access on Teams Preview. No wonder, because it's lacking some features. Will need to wait. Didn't have time to check the logs :(

**Comment by binderth** [comment]
> Unfortunately, can't find this API access on Teams Preview. No wonder, because it's lacking some features

I guess, it's because the new Teams is a complete rewrite and switches from Electron to WebView2 and from Angular to ReactJS. Guess, the logs won't be the same. But my bet is, the local API will be added soon enough, I found out, there's a lot of people using the [Stream Deck integration Plugin](https://apps.elgato.com/plugins/com.microsoft.teams) and it works just perfect!

**Comment by PablaV** [comment]
Any update with this? My organization just updated to the "new" teams app and I no longer see my status in Home Assistant.

**Comment by AntoineGS** [comment]
I hit a wall with my app and haven't pushed further, I'll gather some motivation to do so.
Does the new Teams app have the Third Party Integration option (aka API) yet?

**Comment by PablaV** [comment]
I'm not sure if there is an API for the new app, I did some searches but nothing really came up.

**Comment by PablaV** [comment]
So I checked the New Teams app and there isn't a section with the Third-party app API. I did find where the team's logs are but not sure if those will be useful as you mentioned their logging was cleaned up quite a bit. Maybe we can contact Microsoft and see if they will even have a third party API?

**Comment by binderth** [comment]
I don't think, Microsoft will deprecate the local API. There's a lot of partners using it. I for one use it with my stream deck and would be very unhappy if they discontinued it

https://techcommunity.microsoft.com/t5/healthcare-and-life-sciences/update-4-using-the-native-elgato-stream-deck-integration-with/ba-p/3732044

**Comment by felipecrs** [comment]
![image](https://github.com/AntoineGS/TeamsStatusV2/assets/29582865/ccd3e93c-1e84-47bc-89a9-4cb9f873b545)

There is this option by the way. I don't know what it does though.

And by now everyone can use the new Teams client.

**Comment by binderth** [comment]
I don't know, if you know already, but I think, the API is downwards compatible - at least my Stream Deck Plugin now works after I activated the API on new Teams. Should mean, that classic and new Teams' API uses the same endpoints and attributes.

**Comment by AntoineGS** [comment]
From what I saw last night when testing, the new Teams requires a handshake to generate the token and allow the application to use it, while previously we could generate a token in the UI and use with any application.
I am going to run some tests with postman and see if I can get it to trigger somehow. 
To be continued!

**Comment by AntoineGS** [comment]
I made some good progress over lunch!
I was able to use postman to find the new parameters to pass and was able to get it approved in the New Teams.

I also found this by accident, which is honestly a much better solution and one I was going to tackle after my new application:
https://github.com/malkstar/ms_teams_websockets

It does not seem to have any active development or involvement from the creator though since May.
Do you have any reason to not use a HACS integration?
On my end there is no good reason, I rewrote the application in Rust because I wanted some Rust experience but having it directly in HA is much better.

**Comment by PablaV** [comment]
While I would prefer a HACS integration, the one you linked doesn't seem to be updated for the new Teams. Either way works for me

**Comment by AntoineGS** [comment]
Well it seems the new Teams only allows local connections to the API (same machine), which was not the case with the old API.
That's too bad, this looked very promising.
Back to my Rust project for now.

**Comment by binderth** [comment]
Sorry this was a dead end, but I think, not everyone uses Home Assistant. I for one use openHAB - and built a home assistant mock service with node-Red, which accepted the call from the script and sent mqtt messages...

So, if it would be possible either let the Rust still send "the same"/similar requests to HA. Or let it send mqtt itself? Or let it send other "standard" messages or the like? For folks not using HA? Could be a configuration or something?

**Comment by AntoineGS** [comment]
Sure, I can add an MQTT mode once I wrap up the initial release which
should be shortly.

**Comment by binderth** [comment]
Wow. A Dream!

**Comment by AntoineGS** [comment]
Initial release is done!
Since its not an update but a full rewrite things will most definitely be different.
It should be noted that the WebSocket API does not give the status (Busy, Idle, etc.), the JSON example shows what is available from that API, though I only integrated the video feed and in meeting statuses.
Feel free to open issues on the other project!
