### ISSUE TITLE
Conflicting Status and Activity values when in a call on Teams mobile client

### ISSUE THREAD

**Issue by kitleyn** [AntoineGS/TeamsStatusV2#8]
Status monitoring is configured on my laptop and works well but I have found that whilst in a call/meeting on the Teams mobile client, the values of the Teams Status and Teams Activity show conflicting values. 

Teams Status: On the phone
Teams Activity: Not in a call

I guess because the Activity is only being read from the log file and since there is no ongoing call from the laptop it thinks there isn't a call at all. The Status shows correctly though. 
Any way that a check could be added to the Activity variable to show 'InACall' where the Status is 'OnThePhone', regardless of the logfile.
Thanks

**Comment by AntoineGS** [comment]
That makes a lot of sense, I will make the change!

**Comment by AntoineGS** [comment]
So after some attempts to get this working properly, I have not found a reliable way of getting the status back after hanging up.
Here are a couple of problems I run into:
- Sometimes I do not have a log entry to trigger the script to execute, so the Status gets stuck
- The code that handles Activity changes will not trigger since the activity was not changed on the windows machine, so again the Activity is stuck on "In a call"
- I cannot safely tie the Status and Activity together since you could have a Status of "Available" with an Activity of "In a call" since the interface let's you manually override it

So this said, I don't think I will be pursuing an implementation for this unless someone has a PR for it.
I would recommend changing the Home Assistant code to look for "either Status On the phone or Activity In a call" to get your automations to trigger.
